# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: hyperseeker
ko_fi: hyperseeker
liberapay: Hyperseeker
custom: ['https://www.buymeacoffee.com/hyperseeker']
